# mkdocs.yml

site_name: Pyflunt
site_description: 'Uma biblioteca Python para validações de domínio fluentes, baseada no Domain Notification Pattern.'
site_author: 'Fazedordecodigo'
site_url: 'https://fazedordecodigo.github.io/PyFlunt/'

repo_url: 'https://github.com/fazedordecodigo/PyFlunt'
repo_name: 'fazedordecodigo/PyFlunt'

# Theme
theme:
  name: material
  language: pt
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: 'blue'
      accent: 'light blue'
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: 'blue'
      accent: 'light blue'
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# Navigation
nav:
  - 'Início': 'index.md'
  - 'Guia de Início Rápido': 'getting-started.md'
  - 'Validações':
    - 'Visão Geral': 'validations/index.md'
    - 'Strings e Gerais': 'validations/string.md'
    - 'Numéricas': 'validations/numeric.md'
    - 'Formatos': 'validations/format.md'
    - 'Booleanas': 'validations/boolean.md'
    - 'Documentos Brasileiros': 'validations/brazilian_docs.md'
  - 'Referência da API': 'api-reference.md'
  - 'Sobre o Padrão': 'about.md'
